import Head from "next/head";
import { getAllIds, getUniqueProduct } from "/database/model.js";
import styles from "../../styles/Home.module.css";
import Image from "next/image";
import Link from "next/link";

//nextJs calls getStaticPaths() AND getStaticProps() at build time (deployment)

//getStaticPaths tells nextJs what possible routes there are
//we provide an array of objects like this
//     params: {
//       id: '6'
//     }
//   }
// which tells nextJs how many routes to build at build time
// e.g. six objects in array would mean 6 routes id 1 - 6
export async function getStaticPaths() {
  const allIds = await getAllIds();

  const paths = allIds.map((obj) => {
    return {
      params: { id: String(obj.id) },
    };
  });

  return {
    paths,
    fallback: false,
  };

  // This is what paths array looks like:
  //[
  //   { params: { id: '1' } },
  //   { params: { id: '2' } },
  //   { params: { id: '3' } },
  //   { params: { id: '4' } },
  //   { params: { id: '5' } },
  //   { params: { id: '6' } },
  //   { params: { id: '7' } },
  //   { params: { id: '8' } },
  //   { params: { id: '9' } }
  // ]
}

//getStaticProps collects the product information about a specific product
//by using the param id as argument in our model query called getUniqueProduct
//param.id is whatever goes after /products in the route e.g. /products/3, the param.id = 3
export async function getStaticProps({ params }) {
  //params.id comes from request params
  //this db query is run for each route ONCE at build time to make productData available as a prop
  const productData = await getUniqueProduct(params.id);
  return {
    props: {
      productData,
    },
  };
}

//Accepts productData from staticProps specific to a route
export default function Product({ productData }) {
  // use productData to build out visual image
  const item = productData[0];
  return (
    <div className={styles.container}>
      <main className={styles.productRoutes}>
        <Head>
          <title>Cupcake Store</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <nav className={styles.box}>
          <Link href={"/"}>
            <a className={styles.productNav}>⏎ Back to home</a>
          </Link>
          <Link href={"/basket"}>
            <a className={styles.productNav}>⏎ Basket</a>
          </Link>
        </nav>
        <h1 className={styles.productTitle}>Tasty Cakes</h1>
        <ul className={styles.container}>
          <li key={item.id}>
            <Image
              className={styles.singleImage}
              src={item.url}
              height={200}
              width={200}
              alt="cupcake"
            />
            <h2 className={styles.subheading}>Name:</h2>
            <p className={styles.text}>{item.name}</p>
            <h2 className={styles.subheading}>Description:</h2>
            <p className={styles.text}>{item.description}</p>
            <h2 className={styles.subheading}>Price:</h2>
            <p className={styles.text}>£{item.price.toFixed(2)}</p>
            <h2 className={styles.subheading}>Dietary requirements:</h2>
            <p className={styles.text}>Vegan: {item.vegan ? "✅" : "🚫"}</p>
            <p className={styles.text}>
              No Nuts: {item.nutallergysafe ? "✅" : "🚫"}
            </p>
            <p className={styles.text}>
              Gluten Free: {item.glutenfree ? "✅" : "🚫"}
            </p>
            <p className={styles.text}>
              Dairy Free: {item.dairyfree ? "✅" : "🚫"}
            </p>
            <button className={styles.btn}>
              <a href={"/basket"}>Add to basket</a>
            </button>
          </li>
        </ul>
      </main>
    </div>
  );
}
