import Head from "next/head";
import Image from "next/image";
import ProductCards from "../components/ProductCards";
import { getProductData } from "../database/model";
import styles from "../styles/Home.module.css";

//get product data
export async function getServerSideProps() {
  // db query
  const allProductData = await getProductData();
  // attach this as props to page
  return {
    props: {
      allProductData,
    },
  };
}

export default function Home({ allProductData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cupcake Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <nav className={styles.box}>
          <button className={styles.btn} type="submit">
            Sign Up
          </button>
          <button className={styles.btn} type="button">
            Basket
          </button>
        </nav>
        <div className={styles.container}>
        <h1 className={styles.title}>Cupcake Store</h1>
        <img  src='/unicornCakeLogo.png' height={150} width={200} alt="logo"></img>
        </div>
        <p className={styles.description}>Feeling peckish?</p>

        <div>
          <ProductCards allProductData={allProductData} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel=""
        >
          Contact us at yum@tastycakes.com or on Facebook, Instagram
        </a>
      </footer>
    </div>
  );
}
