import Head from "next/head";
import Image from "next/image";
import React from "react";
import ProductCards from "../components/ProductCards";
import SortControls from "../components/SortControls";
import CategoryControls from "../components/CategoryControls";
import { getProductData } from "../database/model";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import Link from "next/link";

//get product data
export async function getServerSideProps() {
  // db query
  const allProductData = await getProductData();
  // attach this as props to page
  return {
    props: {
      allProductData,
    },
  };
}

export default function Home({ allProductData }) {
  // initial basket state - passed into ProductCards component
  const [basket, setBasket] = useState([]);
  const [sortOrder, setSortOrder] = React.useState("default");
  const [requiredTags, setRequiredTags] = React.useState([
    { vegan: false },
    { nutallergysafe: false },
    { glutenfree: false },
    { dairyfree: false },
  ]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Cupcake Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <nav className={styles.box}>
          {/* <button className={styles.btn} type="submit">
            Sign Up
          </button> */}
          <div className={styles.btn}>
            <Link href={"/basket"}>
              <a>Basket</a>
            </Link>
          </div>
        </nav>
        <div className={styles.container}>
          <h1 className={styles.title}>Cupcake Store</h1>
          <Image
            className={styles.title}
            src="/unicornCakeLogo.png"
            height={150}
            width={200}
            alt="logo"
          />
        </div>

        <aside className={styles.controls}>
          <SortControls
            setSortOrder={setSortOrder}
            sortOrder={sortOrder}
          ></SortControls>
          <CategoryControls
            requiredTags={requiredTags}
            setRequiredTags={setRequiredTags}
          ></CategoryControls>
        </aside>
        <p className={styles.description}>Feeling peckish?</p>

        <div>
          <ProductCards
            allProductData={allProductData}
            sortOrder={sortOrder}
            requiredTags={requiredTags}
            basket={basket}
            setBasket={setBasket}
          />
        </div>
        <footer className={styles.footer}>
          <a href="" target="_blank" rel="">
            Contact us at yum@tastycakes.com or on Facebook, Instagram
          </a>
        </footer>
      </main>
    </div>
  );
}
